corporate_social_responsibility <- list(    
    human_rights = c(
        "\\baboriginal peoples\\b",
        "\\baboriginals\\b",
        "\\babuse\\b",
        "\\baccept\\b",
        "\\baccepted\\b",
        "\\baccommodating\\b",
        "\\baccommodation\\b",
        "\\baccountability\\b",
        "\\bactivities\\b",
        "\\bacts\\b",
        "\\badopt\\b",
        "\\badopted\\b",
        "\\badverse\\b",
        "\\badversely\\b",
        "\\bafrican american\\b",
        "\\bafrican americans\\b",
        "\\bafrican\\b",
        "\\bafricans\\b",
        "\\baged\\b",
        "\\bagent\\b",
        "\\bages\\b",
        "\\bagreements\\b",
        "\\baids\\b",
        "\\balaska natives\\b",
        "\\balaskan natives\\b",
        "\\balternative lifestyle\\b",
        "\\balternative lifestyles\\b",
        "\\balternative lives\\b",
        "\\bavoid\\b",
        "\\baward\\b",
        "\\bawareness\\b",
        "\\bbalancing\\b",
        "\\bbaselines\\b",
        "\\bbelonging\\b",
        "\\bbeneficially\\b",
        "\\bbeneficiary\\b",
        "\\bbenefit\\b",
        "\\bbenefits\\b",
        "\\bbylaws\\b",
        "\\bcare\\b",
        "\\bcertification\\b",
        "\\bcertifications\\b",
        "\\bcertify\\b",
        "\\bcertifying\\b",
        "\\bcharitable\\b",
        "\\bcivil liberties\\b",
        "\\bcivil liberty\\b",
        "\\bcivil rights\\b",
        "\\bcivil\\b",
        "\\bclaims\\b",
        "\\bclass\\b",
        "\\bcoach\\b",
        "\\bcommitments\\b",
        "\\bcommittee\\b",
        "\\bcommunities\\b",
        "\\bcommunity\\b",
        "\\bconstitution\\b",
        "\\bconstitutional right\\b",
        "\\bconstitutional rights\\b",
        "\\bcore\\b",
        "\\bcovenants\\b",
        "\\bcross culturalism\\b",
        "\\bcross culturalisms\\b",
        "\\bcultures\\b",
        "\\bcustodian\\b",
        "\\bdevelopment\\b",
        "\\bdied\\b",
        "\\bdies\\b",
        "\\bdisability\\b",
        "\\bdisabled\\b",
        "\\bdisadvantage\\b",
        "\\bdisadvantaged\\b",
        "\\bdisadvantageous\\b",
        "\\bdisadvantages\\b",
        "\\bdisasters\\b",
        "\\bdiscriminating\\b",
        "\\bdiscrimination\\b",
        "\\bdiscriminatory\\b",
        "\\bdiverse\\b",
        "\\bdiversification\\b",
        "\\bdiversified\\b",
        "\\bdiversify\\b",
        "\\bdiversifying\\b",
        "\\bdiversity\\b",
        "\\bduty\\b",
        "\\beducate\\b",
        "\\beducating\\b",
        "\\beducation\\b",
        "\\beducational\\b",
        "\\belected\\b",
        "\\belection\\b",
        "\\bemploy\\b",
        "\\bemployed\\b",
        "\\bemployee involvement\\b",
        "\\bemployee involvements\\b",
        "\\bemployee\\b",
        "\\bemployees\\b",
        "\\bemployees'\\b",
        "\\bemployees’\\b",
        "\\bemploying\\b",
        "\\bemployment\\b",
        "\\bempower\\b",
        "\\bempowered\\b",
        "\\bempowering\\b",
        "\\bempowerment\\b",
        "\\bempowers\\b",
        "\\benabling\\b",
        "\\bengage\\b",
        "\\bengaging\\b",
        "\\benhancements\\b",
        "\\benhancing\\b",
        "\\bentitled rights\\b",
        "\\bequal opportunities\\b",
        "\\bequal opportunity\\b",
        "\\bequal\\b",
        "\\bequality\\b",
        "\\bequity\\b",
        "\\bergonomically\\b",
        "\\bethic\\b",
        "\\bethical\\b",
        "\\bethically\\b",
        "\\bethnic diversities\\b",
        "\\bethnic diversity\\b",
        "\\bethnic mosaic\\b",
        "\\bethnic mosaics\\b",
        "\\bethnic\\b",
        "\\bethnically\\b",
        "\\bethnicities\\b",
        "\\bethnicity\\b",
        "\\bexercise\\b",
        "\\beyes\\b",
        "\\bface\\b",
        "\\bfair\\b",
        "\\bfairness\\b",
        "\\bfamilies\\b",
        "\\bfamily\\b",
        "\\bfemale\\b",
        "\\bfiduciary\\b",
        "\\bfirst nations\\b",
        "\\bfirst peoples\\b",
        "\\bfree\\b",
        "\\bfreedom\\b",
        "\\bgay\\b",
        "\\bgays\\b",
        "\\bgender diversities\\b",
        "\\bgender diversity\\b",
        "\\bgender\\b",
        "\\bgenders\\b",
        "\\bgod given right\\b",
        "\\bgod given rights\\b",
        "\\bgovernance\\b",
        "\\bhabitat\\b",
        "\\bhazardous\\b",
        "\\bhealthcare\\b",
        "\\bhealthcaring\\b",
        "\\bhire\\b",
        "\\bhiring\\b",
        "\\bhonest\\b",
        "\\bhonesty\\b",
        "\\bhuman development\\b",
        "\\bhumanitarian\\b",
        "\\bhumans\\b",
        "\\bhungry\\b",
        "\\bimprisonment\\b",
        "\\binclusive\\b",
        "\\binclusiveness\\b",
        "\\binfringe\\b",
        "\\binfringement\\b",
        "\\binfringing\\b",
        "\\binterests\\b",
        "\\binvoluntarily\\b",
        "\\binvoluntary\\b",
        "\\binvolve\\b",
        "\\binvolved\\b",
        "\\binvolvement\\b",
        "\\blabor issue\\b",
        "\\blabor issues\\b",
        "\\blabor right\\b",
        "\\blabor rights\\b",
        "\\blabor\\b",
        "\\blawful\\b",
        "\\blawfulness\\b",
        "\\blaws\\b",
        "\\blegal\\b",
        "\\blegality\\b",
        "\\blesbian\\b",
        "\\blesbians\\b",
        "\\blife partner\\b",
        "\\blifestyles\\b",
        "\\bmate\\b",
        "\\bmedicaid\\b",
        "\\bmedicare\\b",
        "\\bmedicinal\\b",
        "\\bminorities\\b",
        "\\bminority\\b",
        "\\bmission\\b",
        "\\bnationality\\b",
        "\\bnationalization\\b",
        "\\bnationalize\\b",
        "\\bnative peoples\\b",
        "\\bnative\\b",
        "\\bnatives\\b",
        "\\bnatural rights\\b",
        "\\boppressive regime\\b",
        "\\boppressive regimes\\b",
        "\\boriginal settlers\\b",
        "\\boutsiders\\b",
        "\\boutsource\\b",
        "\\boutsources\\b",
        "\\boutsourcing\\b",
        "\\bownership\\b",
        "\\bparties\\b",
        "\\bpartner\\b",
        "\\bpartners\\b",
        "\\bpartnerships\\b",
        "\\bpayroll\\b",
        "\\bpeer\\b",
        "\\bpension\\b",
        "\\bpeople\\b",
        "\\bperformance\\b",
        "\\bperformers\\b",
        "\\bperson\\b",
        "\\bpersonal\\b",
        "\\bpersonnel\\b",
        "\\bpersons\\b",
        "\\bphilanthropy\\b",
        "\\bphilosophies\\b",
        "\\bplurality\\b",
        "\\bpoor\\b",
        "\\bprejudiced\\b",
        "\\bprejudices\\b",
        "\\bpreservation\\b",
        "\\bprivileges\\b",
        "\\bprotected\\b",
        "\\bprotections\\b",
        "\\brace\\b",
        "\\braces\\b",
        "\\bracial\\b",
        "\\brape\\b",
        "\\breallocate\\b",
        "\\breallocated\\b",
        "\\brebuilding\\b",
        "\\brecognition\\b",
        "\\bregulate\\b",
        "\\bregulations\\b",
        "\\bregulatory\\b",
        "\\brelations\\b",
        "\\brelationship\\b",
        "\\brelationships\\b",
        "\\breligious diversities\\b",
        "\\breligious diversity\\b",
        "\\breligious\\b",
        "\\breservation\\b",
        "\\brespect for human rights\\b",
        "\\brespect for privacy\\b",
        "\\bretirement\\b",
        "\\bright\\b",
        "\\brights to citizenship\\b",
        "\\bsafety\\b",
        "\\bsalaries\\b",
        "\\bsame sex\\b",
        "\\bscholarships\\b",
        "\\bsexually\\b",
        "\\bshared norms\\b",
        "\\bsick\\b",
        "\\bsocial\\b",
        "\\bspouse\\b",
        "\\bstrengths\\b",
        "\\btalented\\b",
        "\\bteamwork\\b",
        "\\bunalienable rights\\b",
        "\\bunbiased\\b",
        "\\bunconditional\\b",
        "\\bunderrepresented group\\b",
        "\\bunderrepresented groups\\b",
        "\\bunemployable\\b",
        "\\bunemployment\\b",
        "\\bunethical\\b",
        "\\bunfair\\b",
        "\\bunionized\\b",
        "\\bunions\\b",
        "\\bunlawful\\b",
        "\\bvote\\b",
        "\\bvoting\\b",
        "\\bvulnerability\\b",
        "\\bwellness\\b",
        "\\bwheelchair access\\b",
        "\\bwheelchair\\b",
        "\\bwheelchairs\\b",
        "\\bwomen\\b",
        "\\bworkday\\b",
        "\\bworker\\b",
        "\\bworkers’\\b",
        "\\bworkforce\\b",
        "\\bworkforces\\b",
        "\\bworkplaces\\b",
        "\\bworkspaces\\b"
    ),
    employee = c(
        "\\babuse\\b",
        "\\baccommodating\\b",
        "\\baccommodation\\b",
        "\\baccountability\\b",
        "\\badopted child\\b",
        "\\badopted children\\b",
        "\\bafrican american\\b",
        "\\bafrican americans\\b",
        "\\baged\\b",
        "\\balcohol\\b",
        "\\balternative lifestyle\\b",
        "\\balternative lifestyles\\b",
        "\\bamericans with disabilities act\\b",
        "\\bbalancing\\b",
        "\\bbathrooms\\b",
        "\\bbelieving\\b",
        "\\bbeneficially\\b",
        "\\bbeneficiary\\b",
        "\\bbenefit\\b",
        "\\bbenefits\\b",
        "\\bblended families\\b",
        "\\bbody\\b",
        "\\bbonus\\b",
        "\\bboundaries\\b",
        "\\bbylaws\\b",
        "\\bcare\\b",
        "\\bcertification\\b",
        "\\bcertifications\\b",
        "\\bcertify\\b",
        "\\bcertifying\\b",
        "\\bcivil\\b",
        "\\bclaims\\b",
        "\\bclass\\b",
        "\\bcollective well being\\b",
        "\\bcollective well beings\\b",
        "\\bcontribution\\b",
        "\\bcultures\\b",
        "\\bcustodian\\b",
        "\\bcustoms\\b",
        "\\bdevelopment\\b",
        "\\bdied\\b",
        "\\bdies\\b",
        "\\bdirector\\b",
        "\\bdisability\\b",
        "\\bdiscriminating\\b",
        "\\bdiscrimination\\b",
        "\\bdiscriminatory\\b",
        "\\bdiverse\\b",
        "\\bdiversification\\b",
        "\\bdiversified\\b",
        "\\bdiversify\\b",
        "\\bdiversifying\\b",
        "\\bdiversity\\b",
        "\\bdrug\\b",
        "\\beducate\\b",
        "\\beducating\\b",
        "\\beducation\\b",
        "\\beducational programs\\b",
        "\\beducational\\b",
        "\\belected\\b",
        "\\bemploy\\b",
        "\\bemployed\\b",
        "\\bemployee\\b",
        "\\bemployee equity\\b",
        "\\bemployee involvement\\b",
        "\\bemployee relations\\b",
        "\\bemployee safety\\b",
        "\\bemployee welfare\\b",
        "\\bemployee well being\\b",
        "\\bemployee\\b",
        "\\bemployees well being\\b",
        "\\bemployee's well being\\b",
        "\\bemployees\\b",
        "\\bemployees'\\b",
        "\\bemployees’\\b",
        "\\bemployer\\b",
        "\\bemployers\\b",
        "\\bemployers’\\b",
        "\\bemploying\\b",
        "\\bemployment\\b",
        "\\bemploys\\b",
        "\\bempower\\b",
        "\\bempowered\\b",
        "\\bempowering\\b",
        "\\bempowerment\\b",
        "\\bempowers\\b",
        "\\benabling\\b",
        "\\bengage\\b",
        "\\bengaging\\b",
        "\\benhancements\\b",
        "\\benhancing\\b",
        "\\benjoyable\\b",
        "\\benvironment\\b",
        "\\bequal opportunity\\b",
        "\\bequal\\b",
        "\\bequity\\b",
        "\\bergonomically\\b",
        "\\bethic\\b",
        "\\bethically\\b",
        "\\bethnic diversity\\b",
        "\\bethnic\\b",
        "\\bethnicities\\b",
        "\\bethnicity\\b",
        "\\beven distribution\\b",
        "\\beven\\b",
        "\\bevenly distributed\\b",
        "\\bexercise\\b",
        "\\bexperience\\b",
        "\\bexperienced\\b",
        "\\bextended families\\b",
        "\\bextended family\\b",
        "\\bfair\\b",
        "\\bfairness\\b",
        "\\bfamilies\\b",
        "\\bfamily\\b",
        "\\bfemale\\b",
        "\\bfiduciary\\b",
        "\\bfreedom\\b",
        "\\bgay\\b",
        "\\bgays\\b",
        "\\bgender diversity\\b",
        "\\bgoal\\b",
        "\\bgoals\\b",
        "\\bgovernance\\b",
        "\\bgreen card\\b",
        "\\bhard work\\b",
        "\\bhealth benefits\\b",
        "\\bhealth care benefits\\b",
        "\\bhealth insurance\\b",
        "\\bhealth\\b",
        "\\bhealthcare\\b",
        "\\bhealthcaring\\b",
        "\\bhealthy\\b",
        "\\bhire\\b",
        "\\bhiring\\b",
        "\\bhumanitarian\\b",
        "\\bhumans\\b",
        "\\bincentives\\b",
        "\\bindividual\\b",
        "\\bindividually\\b",
        "\\binfringe\\b",
        "\\binfringement\\b",
        "\\binfringing\\b",
        "\\binsurance\\b",
        "\\binternal stakeholder\\b",
        "\\binternal stakeholders\\b",
        "\\binvolved\\b",
        "\\bjobs\\b",
        "\\bknowledge\\b",
        "\\bknowledgeable\\b",
        "\\bknowledgebase\\b",
        "\\blabor rights\\b",
        "\\blabor\\b",
        "\\blaborers\\b",
        "\\blawfulness\\b",
        "\\blaws\\b",
        "\\bleader\\b",
        "\\bleaders\\b",
        "\\bleadership\\b",
        "\\blearned\\b",
        "\\blearning\\b",
        "\\blegal\\b",
        "\\blesbian\\b",
        "\\blesbians\\b",
        "\\blife benefits\\b",
        "\\blife partner\\b",
        "\\blifestyles\\b",
        "\\blives\\b",
        "\\bliving\\b",
        "\\bmanagement\\b",
        "\\bmate\\b",
        "\\bmeals\\b",
        "\\bmedicaid\\b",
        "\\bmedicare\\b",
        "\\bmedicinal\\b",
        "\\bminorities\\b",
        "\\bminority\\b",
        "\\bmission\\b",
        "\\bmoral\\b",
        "\\bmortality\\b",
        "\\bmultinational\\b",
        "\\bnative\\b",
        "\\bnonemployee\\b",
        "\\bnonrenewal\\b",
        "\\boccupational\\b",
        "\\bofficer\\b",
        "\\bofficers\\b",
        "\\boutsourcing\\b",
        "\\bpaid time off\\b",
        "\\bpaid vacation time\\b",
        "\\bpaid\\b",
        "\\bparticipant\\b",
        "\\bparticipants\\b",
        "\\bparticipating\\b",
        "\\bparticipatory\\b",
        "\\bparties\\b",
        "\\bpartner\\b",
        "\\bpayroll\\b",
        "\\bpeer\\b",
        "\\bpension\\b",
        "\\bpeople\\b",
        "\\bperformance\\b",
        "\\bperformers\\b",
        "\\bperson\\b",
        "\\bpersonal\\b",
        "\\bpersonnel\\b",
        "\\bpersons\\b",
        "\\bphilosophies\\b",
        "\\bpositions\\b",
        "\\bpractices\\b",
        "\\bprejudiced\\b",
        "\\bprescribed\\b",
        "\\bprinciples\\b",
        "\\bprivileges\\b",
        "\\bproductivity\\b",
        "\\bprofessional\\b",
        "\\bprofessionals\\b",
        "\\bprofit sharing\\b",
        "\\bpromotion\\b",
        "\\bprotected\\b",
        "\\bquality\\b",
        "\\brace\\b",
        "\\brape\\b",
        "\\brate\\b",
        "\\breallocate\\b",
        "\\breallocated\\b",
        "\\brecognition\\b",
        "\\brecognize\\b",
        "\\brecognized\\b",
        "\\bregulate\\b",
        "\\bregulations\\b",
        "\\bregulatory\\b",
        "\\breimburse\\b",
        "\\brelations\\b",
        "\\brelationship\\b",
        "\\brelationships\\b",
        "\\breligious diversity\\b",
        "\\breligious\\b",
        "\\brespects\\b",
        "\\bresponsibility\\b",
        "\\bresponsible\\b",
        "\\bretirement\\b",
        "\\bright\\b",
        "\\brole\\b",
        "\\bsafe\\b",
        "\\bsafety\\b",
        "\\bsalaries\\b",
        "\\bsatisfaction\\b",
        "\\bscholarships\\b",
        "\\bseasonal\\b",
        "\\bselection\\b",
        "\\bsensitivity\\b",
        "\\bserved\\b",
        "\\bserves\\b",
        "\\bservice\\b",
        "\\bservices\\b",
        "\\bsexually\\b",
        "\\bshared norms\\b",
        "\\bsick\\b",
        "\\bsize\\b",
        "\\bsocial wellbeing\\b",
        "\\bsocial\\b",
        "\\bsocially\\b",
        "\\bspousal relationship\\b",
        "\\bspousal relationships\\b",
        "\\bspouse\\b",
        "\\bstakeholders\\b",
        "\\bstrengths\\b",
        "\\bsuitability\\b",
        "\\bsuitable\\b",
        "\\bsustain\\b",
        "\\bsustains\\b",
        "\\btalented\\b",
        "\\bteam\\b",
        "\\bteams\\b",
        "\\bteamwork\\b",
        "\\btenure\\b",
        "\\btrained\\b",
        "\\btrust\\b",
        "\\btruthfulness\\b",
        "\\btuition reimbursement\\b",
        "\\bunderstand\\b",
        "\\bundocumented aliens\\b",
        "\\bundocumented\\b",
        "\\bunemployable\\b",
        "\\bunemployment\\b",
        "\\bunethical\\b",
        "\\bunfair\\b",
        "\\bunion\\b",
        "\\bunionized\\b",
        "\\bunions\\b",
        "\\bunproductive\\b",
        "\\bunsafe\\b",
        "\\bvacation time\\b",
        "\\bvision benefit\\b",
        "\\bvision benefits\\b",
        "\\bwage\\b",
        "\\bwear\\b",
        "\\bwelfare\\b",
        "\\bwellness\\b",
        "\\bwheelchair access\\b",
        "\\bwheelchair\\b",
        "\\bwheelchairs\\b",
        "\\bwife\\b",
        "\\bwomen\\b",
        "\\bwork\\b",
        "\\bworkday\\b",
        "\\bworker\\b",
        "\\bworkers\\b",
        "\\bworkers’\\b",
        "\\bworkforce\\b",
        "\\bworkforces\\b",
        "\\bworking class\\b",
        "\\bworking men and women\\b",
        "\\bwork life balance\\b",
        "\\bworkmen\\b",
        "\\bworkplaces\\b",
        "\\bworks\\b",
        "\\bworkspaces\\b"
    ),
    social_and_community = c(
        "\\babuse\\b",
        "\\babused\\b",
        "\\babuses\\b",
        "\\baccept\\b",
        "\\baccepted\\b",
        "\\baccommodating\\b",
        "\\baccommodation\\b",
        "\\baccompanied\\b",
        "\\baccountability\\b",
        "\\baccountancy\\b",
        "\\bactivities\\b",
        "\\badopt\\b",
        "\\badopted\\b",
        "\\baffordable housing\\b",
        "\\baffordable\\b",
        "\\baged\\b",
        "\\bages\\b",
        "\\baids\\b",
        "\\bamerican\\b",
        "\\barms\\b",
        "\\bbeneficially\\b",
        "\\bbeneficiary\\b",
        "\\bbenefit the masses\\b",
        "\\bbenefit\\b",
        "\\bbenefits\\b",
        "\\bbribe\\b",
        "\\bbuilding\\b",
        "\\bcertification\\b",
        "\\bcertifications\\b",
        "\\bcertify\\b",
        "\\bcertifying\\b",
        "\\bcharitability\\b",
        "\\bcharitable foundation\\b",
        "\\bcharitable giving\\b",
        "\\bcharitable\\b",
        "\\bcharitably\\b",
        "\\bcharities\\b",
        "\\bcharity\\b",
        "\\bcharity\\b",
        "\\bchild labor\\b",
        "\\bchild laborers\\b",
        "\\bcivic duties\\b",
        "\\bcivic duty\\b",
        "\\bcivic engagement\\b",
        "\\bcivic engagements\\b",
        "\\bcivic\\b",
        "\\bcivil\\b",
        "\\bclass\\b",
        "\\bclean\\b",
        "\\bcleaned\\b",
        "\\bcleaner\\b",
        "\\bcleaning\\b",
        "\\bcleanliness\\b",
        "\\bcleanup\\b",
        "\\bcollective well being\\b",
        "\\bcollective well beings\\b",
        "\\bcollectively\\b",
        "\\bcommitments\\b",
        "\\bcommon\\b",
        "\\bcommunal\\b",
        "\\bcommunities\\b",
        "\\bcommunity development\\b",
        "\\bcommunity developments\\b",
        "\\bcommunity group\\b",
        "\\bcommunity groups\\b",
        "\\bcommunity impact\\b",
        "\\bcommunity minded\\b",
        "\\bcommunity mission\\b",
        "\\bcommunity outreach\\b",
        "\\bcommunity policies\\b",
        "\\bcommunity policy\\b",
        "\\bcommunity project\\b",
        "\\bcommunity projects\\b",
        "\\bcommunity\\b",
        "\\bconcern\\b",
        "\\bconflict mineral\\b",
        "\\bconflict minerals\\b",
        "\\bcontribution\\b",
        "\\bcorporate foundation\\b",
        "\\bcountries\\b",
        "\\bcountry\\b",
        "\\bcounty\\b",
        "\\bcsr\\b",
        "\\bcultural preservation\\b",
        "\\bcultures\\b",
        "\\bcustodian\\b",
        "\\bdelegation\\b",
        "\\bdemographic\\b",
        "\\bdevelopment\\b",
        "\\bdiet\\b",
        "\\bdisability\\b",
        "\\bdisable\\b",
        "\\bdisabled\\b",
        "\\bdisclosure\\b",
        "\\bdisclosures\\b",
        "\\bdiverse\\b",
        "\\bdiversification\\b",
        "\\bdiversified\\b",
        "\\bdiversify\\b",
        "\\bdiversifying\\b",
        "\\bdiversity\\b",
        "\\bdrinking\\b",
        "\\beducate\\b",
        "\\beducating\\b",
        "\\beducation\\b",
        "\\beducational\\b",
        "\\belected\\b",
        "\\belection\\b",
        "\\bemploy\\b",
        "\\bemployed\\b",
        "\\bemploying\\b",
        "\\bemployment\\b",
        "\\bemploys\\b",
        "\\bempower\\b",
        "\\bempowered\\b",
        "\\bempowering\\b",
        "\\bempowerment\\b",
        "\\bempowers\\b",
        "\\benabling\\b",
        "\\bengage\\b",
        "\\bengaging\\b",
        "\\bequal\\b",
        "\\bethic\\b",
        "\\bethically\\b",
        "\\bfairness\\b",
        "\\bfamilies\\b",
        "\\bfamily\\b",
        "\\bfemale\\b",
        "\\bfood pantries\\b",
        "\\bfood pantry\\b",
        "\\bfoodbank\\b",
        "\\bfoodbanks\\b",
        "\\bfreedom\\b",
        "\\bfund\\b",
        "\\bfundraising\\b",
        "\\bfunds\\b",
        "\\bfuture\\b",
        "\\bfuture generation\\b",
        "\\bfuture generations\\b",
        "\\bgiving\\b",
        "\\bgovernment\\b",
        "\\bgovernments\\b",
        "\\bgroups of stakeholders\\b",
        "\\bhabitat\\b",
        "\\bhealthcare\\b",
        "\\bhealthcaring\\b",
        "\\bhelp\\b",
        "\\bhope\\b",
        "\\bhuman being\\b",
        "\\bhuman\\b",
        "\\bhumanitarian\\b",
        "\\bhumans\\b",
        "\\bhungry\\b",
        "\\bimpact on community\\b",
        "\\bimpact on local communities\\b",
        "\\bimpact on local community\\b",
        "\\bimpact on society\\b",
        "\\bimprove\\b",
        "\\bimprovements\\b",
        "\\bindigenous\\b",
        "\\bindigenous people\\b",
        "\\bindigenous peoples\\b",
        "\\binnovation\\b",
        "\\bintelligence\\b",
        "\\binvolve\\b",
        "\\binvolved\\b",
        "\\binvolvement\\b",
        "\\bjeopardize\\b",
        "\\bjeopardized\\b",
        "\\bjeopardizes\\b",
        "\\bjeopardizing\\b",
        "\\bjob creation\\b",
        "\\blabor\\b",
        "\\blawfulness\\b",
        "\\blaws\\b",
        "\\blead\\b",
        "\\bleadership\\b",
        "\\blearned\\b",
        "\\blearning\\b",
        "\\blegal\\b",
        "\\bless fortunate\\b",
        "\\blife benefits\\b",
        "\\blifestyles\\b",
        "\\blives\\b",
        "\\bliving\\b",
        "\\blocal community\\b",
        "\\blocal development\\b",
        "\\blocal developments\\b",
        "\\blocale\\b",
        "\\bmeaningful\\b",
        "\\bmedicaid\\b",
        "\\bmedicare\\b",
        "\\bmedicinal\\b",
        "\\bminimize\\b",
        "\\bminority\\b",
        "\\bmission\\b",
        "\\bmoral\\b",
        "\\bmortality\\b",
        "\\bmultinational\\b",
        "\\bnative people\\b",
        "\\bnative peoples\\b",
        "\\bnative\\b",
        "\\bnatural\\b",
        "\\bnaturally\\b",
        "\\bnature\\b",
        "\\bnot for profit\\b",
        "\\bopen\\b",
        "\\boppressive regimes\\b",
        "\\borganizational involvement\\b",
        "\\borganization's involvement\\b",
        "\\borphan\\b",
        "\\borphans\\b",
        "\\boutperform\\b",
        "\\boutsource\\b",
        "\\boutsources\\b",
        "\\boutsourcing\\b",
        "\\bownership\\b",
        "\\bowns\\b",
        "\\bparticipant\\b",
        "\\bparticipants\\b",
        "\\bparticipating\\b",
        "\\bparties\\b",
        "\\bpartner\\b",
        "\\bpartners\\b",
        "\\bpartnerships\\b",
        "\\bparty\\b",
        "\\bpeople group\\b",
        "\\bpeople groups\\b",
        "\\bpeople\\b",
        "\\bperformance\\b",
        "\\bperformers\\b",
        "\\bperson\\b",
        "\\bpersonal\\b",
        "\\bpersons\\b",
        "\\bphilanthropic\\b",
        "\\bphilanthropies\\b",
        "\\bphilanthropy\\b",
        "\\bphilosophies\\b",
        "\\bplan\\b",
        "\\bplurality\\b",
        "\\bpoor individual\\b",
        "\\bpoor individuals\\b",
        "\\bpoor people\\b",
        "\\bpoor\\b",
        "\\bprejudiced\\b",
        "\\bprejudices\\b",
        "\\bpreservation\\b",
        "\\bpreserve culture\\b",
        "\\bprevented\\b",
        "\\bprinciples\\b",
        "\\bprivileges\\b",
        "\\bprofit sharing\\b",
        "\\bprojects\\b",
        "\\bprotected\\b",
        "\\bprotections\\b",
        "\\bpublicly\\b",
        "\\brace\\b",
        "\\brape\\b",
        "\\brebuilding\\b",
        "\\brecognition\\b",
        "\\brecognize\\b",
        "\\brecognized\\b",
        "\\brecovery\\b",
        "\\bredeemable\\b",
        "\\breduce\\b",
        "\\breduces\\b",
        "\\bregulate\\b",
        "\\bregulations\\b",
        "\\bregulatory\\b",
        "\\brelations\\b",
        "\\brelationship\\b",
        "\\brelationships\\b",
        "\\breliability\\b",
        "\\breligious\\b",
        "\\brely\\b",
        "\\brenew\\b",
        "\\brenovation\\b",
        "\\brespect\\b",
        "\\brespects\\b",
        "\\bresponsibility\\b",
        "\\bresponsible\\b",
        "\\brole\\b",
        "\\bsafe\\b",
        "\\bsafety\\b",
        "\\bscholarships\\b",
        "\\bservice\\b",
        "\\bservices\\b",
        "\\bshared norms\\b",
        "\\bsick\\b",
        "\\bsocial activities\\b",
        "\\bsocial inclination\\b",
        "\\bsocial issue\\b",
        "\\bsocial issues\\b",
        "\\bsocial policies\\b",
        "\\bsocial policies\\b",
        "\\bsocial policy\\b",
        "\\bsocial policy\\b",
        "\\bsocial\\b",
        "\\bsocially inclined\\b",
        "\\bsocially minded\\b",
        "\\bsocially\\b",
        "\\bsocietal\\b",
        "\\bsocietal development\\b",
        "\\bsocietal developments\\b",
        "\\bsocietal developments\\b",
        "\\bsocietal impact\\b",
        "\\bsponsors'\\b",
        "\\bsponsorship\\b",
        "\\bstakeholders\\b",
        "\\bsustain\\b",
        "\\bsustainability\\b",
        "\\bsustainable\\b",
        "\\bsustained\\b",
        "\\bsustaining\\b",
        "\\bsustains\\b",
        "\\bsweat shops\\b",
        "\\btalented\\b",
        "\\bteam\\b",
        "\\bteams\\b",
        "\\btrained\\b",
        "\\btransparency\\b",
        "\\btransparent\\b",
        "\\btrust\\b",
        "\\btrustees\\b",
        "\\btruthfulness\\b",
        "\\bunconditional\\b",
        "\\bunemployable\\b",
        "\\bunethical\\b",
        "\\bunfair\\b",
        "\\bunfriendly\\b",
        "\\bunionized\\b",
        "\\bunions\\b",
        "\\bunited\\b",
        "\\bunrestricted\\b",
        "\\bunsafe\\b",
        "\\buprooting\\b",
        "\\burban planning\\b",
        "\\burban\\b",
        "\\burbanization\\b",
        "\\bvoluntarily\\b",
        "\\bvoluntary\\b",
        "\\bvolunteer\\b",
        "\\bvolunteerism\\b",
        "\\bvolunteers\\b",
        "\\bvote\\b",
        "\\bvoting\\b",
        "\\bvulnerability\\b",
        "\\bvulnerable\\b",
        "\\bwater\\b",
        "\\bwaters\\b",
        "\\bwell being\\b",
        "\\bwell beings\\b",
        "\\bwellness\\b",
        "\\bwomen\\b",
        "\\bwork\\b",
        "\\bworld\\b",
        "\\bwrongdoers\\b",
        "\\bwrongdoing\\b",
        "\\bwrongfully\\b",
        "\\bzone\\b",
        "\\bzones\\b"
    ),
    environment = c(
        "\\babuse\\b",
        "\\baccept\\b",
        "\\baccepted\\b",
        "\\baccommodating\\b",
        "\\baccommodation\\b",
        "\\baccountability\\b",
        "\\bacid rain\\b",
        "\\bacid rains\\b",
        "\\bactivities\\b",
        "\\badopt\\b",
        "\\badopted\\b",
        "\\badverse\\b",
        "\\badversely\\b",
        "\\baffluence\\b",
        "\\baffluences\\b",
        "\\bagreements\\b",
        "\\bagricultural\\b",
        "\\bagriculture\\b",
        "\\bagro\\b",
        "\\baids\\b",
        "\\bair filtration\\b",
        "\\balternative energy\\b",
        "\\bamazon rain forest\\b",
        "\\bamazon\\b",
        "\\bancient ruins\\b",
        "\\banimal\\b",
        "\\banti\\b",
        "\\barms\\b",
        "\\bassurance\\b",
        "\\battention\\b",
        "\\battributable\\b",
        "\\baudit\\b",
        "\\bauditor\\b",
        "\\bauditors\\b",
        "\\bauthenticate\\b",
        "\\bauthenticity\\b",
        "\\bawareness\\b",
        "\\bbalancing\\b",
        "\\bbarge\\b",
        "\\bbaselines\\b",
        "\\bbasin\\b",
        "\\bbeautiful\\b",
        "\\bbeauty\\b",
        "\\bbeneficially\\b",
        "\\bbeneficiary\\b",
        "\\bbenefit\\b",
        "\\bbenefits\\b",
        "\\bbio diversities\\b",
        "\\bbiodiversity\\b",
        "\\bboard\\b",
        "\\bbody\\b",
        "\\bboundaries\\b",
        "\\bbribe\\b",
        "\\bbroad\\b",
        "\\bbromides\\b",
        "\\bbromine\\b",
        "\\bbromines\\b",
        "\\bbuilding\\b",
        "\\bbull\\b",
        "\\bburn\\b",
        "\\bbylaws\\b",
        "\\bcage\\b",
        "\\bcaged animal\\b",
        "\\bcaged animals\\b",
        "\\bcarbon dioxide\\b",
        "\\bcarbon dioxides\\b",
        "\\bcarbon disclosure\\b",
        "\\bcarbon disclosures\\b",
        "\\bcarbon emission\\b",
        "\\bcarbon emissions\\b",
        "\\bcarbon\\b",
        "\\bcarbonate\\b",
        "\\bcarbonated\\b",
        "\\bcarbonates\\b",
        "\\bcarbons\\b",
        "\\bcarrying capacities\\b",
        "\\bcarrying capacity\\b",
        "\\bcarrying load\\b",
        "\\bcarrying loads\\b",
        "\\bcatastrophic\\b",
        "\\bchemicals\\b",
        "\\bchloride\\b",
        "\\bchlorine\\b",
        "\\bcity\\b",
        "\\bcivil\\b",
        "\\bclean energies\\b",
        "\\bclean energy\\b",
        "\\bclimate change\\b",
        "\\bclimate changes\\b",
        "\\bclimate event\\b",
        "\\bclimate\\b",
        "\\bco2\\b",
        "\\bcode\\b",
        "\\bcollective well being\\b",
        "\\bconflict mineral\\b",
        "\\bconflict minerals\\b",
        "\\bconservation\\b",
        "\\bconservationist\\b",
        "\\bconservationists\\b",
        "\\bconservations\\b",
        "\\bconserve\\b",
        "\\bcorn\\b",
        "\\bcorporate\\b",
        "\\bcounties\\b",
        "\\bcountries\\b",
        "\\bcountry\\b",
        "\\bcovenants\\b",
        "\\bcrops\\b",
        "\\bcrud\\b",
        "\\bcultivation\\b",
        "\\bcustodian\\b",
        "\\bcustoms\\b",
        "\\bcycle\\b",
        "\\bdelegation\\b",
        "\\bdemographic\\b",
        "\\bdepleted\\b",
        "\\bdepletes\\b",
        "\\bdepleting\\b",
        "\\bdepletion\\b",
        "\\bdepletions\\b",
        "\\bdesign\\b",
        "\\bdioxide\\b",
        "\\bdioxides\\b",
        "\\bdisclosing\\b",
        "\\bdisclosure\\b",
        "\\bdisposal\\b",
        "\\bdiverse\\b",
        "\\bdiversification\\b",
        "\\bdiversified\\b",
        "\\bdiversify\\b",
        "\\bdiversifying\\b",
        "\\bdouble bottom line\\b",
        "\\bdwindling\\b",
        "\\beasements\\b",
        "\\becological\\b",
        "\\beco system\\b",
        "\\beco systems\\b",
        "\\beducate\\b",
        "\\beducating\\b",
        "\\beducation\\b",
        "\\beducational\\b",
        "\\befficiencies\\b",
        "\\befficiently\\b",
        "\\bemission\\b",
        "\\bemissions\\b",
        "\\bemploy\\b",
        "\\benergy efficiencies\\b",
        "\\benergy efficiency\\b",
        "\\benergy efficient\\b",
        "\\benergy star\\b",
        "\\benhancements\\b",
        "\\benhancing\\b",
        "\\benvironment\\b",
        "\\benvironmental activism\\b",
        "\\benvironmental activist\\b",
        "\\benvironmental activists\\b",
        "\\benvironmental activities\\b",
        "\\benvironmental activity\\b",
        "\\benvironmental disclosure\\b",
        "\\benvironmental disclosures\\b",
        "\\benvironmental impact\\b",
        "\\benvironmental inclination\\b",
        "\\benvironmental management systems (ems)\\b",
        "\\benvironmental performance\\b",
        "\\benvironmental policies\\b",
        "\\benvironmental policy\\b",
        "\\benvironmental position\\b",
        "\\benvironmental positions\\b",
        "\\benvironmental protection agency\\b",
        "\\benvironmental reform\\b",
        "\\benvironmental reformation\\b",
        "\\benvironmental resource\\b",
        "\\benvironmental resources\\b",
        "\\benvironmental responsibilities\\b",
        "\\benvironmental responsibility\\b",
        "\\benvironmental safety\\b",
        "\\benvironmental stance\\b",
        "\\benvironmental stewardship\\b",
        "\\benvironmental\\b",
        "\\benvironmentalist\\b",
        "\\benvironmentalists\\b",
        "\\benvironmentally friendly\\b",
        "\\benvironmentally inclined\\b",
        "\\benvironmentally safe\\b",
        "\\benvironmentally\\b",
        "\\bepa standards\\b",
        "\\bepa\\b",
        "\\bequip\\b",
        "\\besg\\b",
        "\\bethic\\b",
        "\\bethically\\b",
        "\\bevolution\\b",
        "\\bexceed capacity\\b",
        "\\bexceeded capacity\\b",
        "\\bexceeds capacity\\b",
        "\\bexcess capacities\\b",
        "\\bexcess capacity\\b",
        "\\bexit\\b",
        "\\bexpand\\b",
        "\\bfacility\\b",
        "\\bfair\\b",
        "\\bfairness\\b",
        "\\bfarm fresh\\b",
        "\\bfarm\\b",
        "\\bfarmer\\b",
        "\\bfarmland\\b",
        "\\bfarmlands\\b",
        "\\bflammability\\b",
        "\\bflies\\b",
        "\\bfoodservice\\b",
        "\\bfossil\\b",
        "\\bfossils\\b",
        "\\bfree range animal\\b",
        "\\bfree range animals\\b",
        "\\bfree range animals\\b",
        "\\bfree range\\b",
        "\\bfree\\b",
        "\\bfreedom\\b",
        "\\bfundraising\\b",
        "\\bfunds\\b",
        "\\bgenetically modified\\b",
        "\\bglobal warming\\b",
        "\\bglobal warming\\b",
        "\\bgold\\b",
        "\\bgood profit\\b",
        "\\bgreen building\\b",
        "\\bgreen buildings\\b",
        "\\bgreen engineering\\b",
        "\\bgri frameworks\\b",
        "\\bgri ratings\\b",
        "\\bgri standards\\b",
        "\\bgri\\b",
        "\\bgroundwater\\b",
        "\\bgroves\\b",
        "\\bgrow\\b",
        "\\bguidelines\\b",
        "\\bharm\\b",
        "\\bharmony\\b",
        "\\bharness wind energy\\b",
        "\\bharness wind power\\b",
        "\\bhazardous waste\\b",
        "\\bhazardous\\b",
        "\\bhcfc\\b",
        "\\bhistoric sites\\b",
        "\\bhumanitarian\\b",
        "\\bhumans\\b",
        "\\bhungry\\b",
        "\\bhybrid car\\b",
        "\\bhybrid energy\\b",
        "\\bhybrid vehicle\\b",
        "\\bhybrid vehicles\\b",
        "\\bhybrid\\b",
        "\\bhydrogen power\\b",
        "\\bhydrogen powered\\b",
        "\\bhydro power\\b",
        "\\bhydro powered\\b",
        "\\biirc\\b",
        "\\bimpairments\\b",
        "\\bimplementing\\b",
        "\\bimprove\\b",
        "\\bimprovements\\b",
        "\\bincentives\\b",
        "\\bindemnification\\b",
        "\\bindependent\\b",
        "\\bindications\\b",
        "\\binfringe\\b",
        "\\binfringement\\b",
        "\\binfringing\\b",
        "\\binnovation\\b",
        "\\biso\\b",
        "\\bkld categories\\b",
        "\\bkld standards\\b",
        "\\bkld\\b",
        "\\bland conservation\\b",
        "\\bland conservationism\\b",
        "\\bland conservationist\\b",
        "\\bland conservationists\\b",
        "\\blifestyle of health and sustainability\\b",
        "\\blives\\b",
        "\\bliving\\b",
        "\\blocale\\b",
        "\\bmaintenance\\b",
        "\\bmaps\\b",
        "\\bmaterial stewardship\\b",
        "\\bmaterials\\b",
        "\\bmaximum capacities\\b",
        "\\bmaximum capacity\\b",
        "\\bmeaningful\\b",
        "\\bmembers\\b",
        "\\bmigration\\b",
        "\\bmsci\\b",
        "\\bnatural resource\\b",
        "\\bnatural resources\\b",
        "\\bnatural\\b",
        "\\bnature\\b",
        "\\bnuclear\\b",
        "\\borganic\\b",
        "\\bovercapacity\\b",
        "\\boxidation\\b",
        "\\bozone depleting\\b",
        "\\bozone depletion\\b",
        "\\bozone depletions\\b",
        "\\bozone\\b",
        "\\bpetroleum\\b",
        "\\bpipelines\\b",
        "\\bplant\\b",
        "\\bpollutant\\b",
        "\\bpollutants\\b",
        "\\bpolluting\\b",
        "\\bpollution prevention\\b",
        "\\bpollution\\b",
        "\\bpower\\b",
        "\\bpractices\\b",
        "\\bpreservation\\b",
        "\\bpreserve way of life\\b",
        "\\bpreserve\\b",
        "\\bpreserves\\b",
        "\\bprevention\\b",
        "\\bpro environmental\\b",
        "\\bpurification\\b",
        "\\bquality\\b",
        "\\brainforest\\b",
        "\\breasonable\\b",
        "\\brebuilding\\b",
        "\\brecoverable\\b",
        "\\breduce\\b",
        "\\breduces\\b",
        "\\bregulate\\b",
        "\\brenew\\b",
        "\\brenewable energies\\b",
        "\\brenewable energy\\b",
        "\\brenewable\\b",
        "\\brenewal\\b",
        "\\brenewals\\b",
        "\\brenewed\\b",
        "\\brenewing\\b",
        "\\brequirements\\b",
        "\\bresearch\\b",
        "\\bresearchers\\b",
        "\\breserve\\b",
        "\\breserves\\b",
        "\\breservoir\\b",
        "\\bresource conservation\\b",
        "\\bresource conservationism\\b",
        "\\bresource conservationist\\b",
        "\\bresource conservationists\\b",
        "\\brespects\\b",
        "\\bresponsibility\\b",
        "\\bresponsible\\b",
        "\\breusable\\b",
        "\\breuse\\b",
        "\\breuses\\b",
        "\\bright\\b",
        "\\briver\\b",
        "\\broyalties\\b",
        "\\bsafe\\b",
        "\\bsafety\\b",
        "\\bsaltwater\\b",
        "\\bscience\\b",
        "\\bscientifically\\b",
        "\\bscientists\\b",
        "\\bseasonal\\b",
        "\\bseasonally\\b",
        "\\bseed\\b",
        "\\bselection\\b",
        "\\bsensitivity\\b",
        "\\bshipyards\\b",
        "\\bshore\\b",
        "\\bshrinking\\b",
        "\\bsite\\b",
        "\\bsmart growth\\b",
        "\\bsolar\\b",
        "\\bsolubility\\b",
        "\\bsolvents\\b",
        "\\bsourcing\\b",
        "\\bstakeholders\\b",
        "\\bstewardship\\b",
        "\\bsuitability\\b",
        "\\bsuitable\\b",
        "\\bsulfur\\b",
        "\\bsurveys\\b",
        "\\bsustain\\b",
        "\\bsustainable consumption\\b",
        "\\bsustainable\\b",
        "\\bsymbiotic relationship\\b",
        "\\bsymbiotic relationships\\b",
        "\\bsymbiotic\\b",
        "\\btarget\\b",
        "\\btechnologies\\b",
        "\\btemperature rise\\b",
        "\\bterrorist\\b",
        "\\bthreat\\b",
        "\\btornadoes\\b",
        "\\btradeoffs\\b",
        "\\btransparency\\b",
        "\\btransparent\\b",
        "\\btree\\b",
        "\\btriple bottom line\\b",
        "\\btruthfulness\\b",
        "\\bturbine\\b",
        "\\bunavoidable\\b",
        "\\bunbiased\\b",
        "\\bunderutilization\\b",
        "\\bunderutilized\\b",
        "\\buneconomic\\b",
        "\\buneconomical\\b",
        "\\buneconomically\\b",
        "\\bunethical\\b",
        "\\bunfair\\b",
        "\\bunproductive\\b",
        "\\bunprofitably\\b",
        "\\bunrestricted\\b",
        "\\bunsafe\\b",
        "\\bunusable\\b",
        "\\buprooting\\b",
        "\\burbanization\\b",
        "\\bvegetables\\b",
        "\\bvolcanic\\b",
        "\\bvoluntarily\\b",
        "\\bvoluntary disclosure\\b",
        "\\bvoluntary disclosures\\b",
        "\\bvoluntary\\b",
        "\\bvulnerability\\b",
        "\\bvulnerable\\b",
        "\\bwarm\\b",
        "\\bwaste reduction\\b",
        "\\bwaste\\b",
        "\\bwasteland\\b",
        "\\bwater desalination\\b",
        "\\bwater purification\\b",
        "\\bwater purifications\\b",
        "\\bwater\\b",
        "\\bwave\\b",
        "\\bweather\\b",
        "\\bwetland\\b",
        "\\bwetlands\\b",
        "\\bwilderness\\b",
        "\\bwildlife conservation\\b",
        "\\bwind energies\\b",
        "\\bwind energy\\b",
        "\\bwind\\b",
        "\\bwindmill\\b",
        "\\bwood\\b",
        "\\bworld\\b",
        "\\bwrongdoing\\b",
        "\\bwrongfully\\b",
        "\\byard\\b",
        "\\byields\\b",
        "\\bzone\\b",
        "\\bzones\\b",
        "\\bzoning\\b"
    )
)



if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, textshape, data.tree)

key_corporate_social_responsibility  <- corporate_social_responsibility  %>%
    textshape::tidy_list('dimension', 'regex') %>%
    mutate(
        token = gsub('\\\\b', '', regex),
        token = gsub('’', "'", token),
        regex = gsub('’', "'", regex)   
    ) %>%
    as_tibble() %>%
    mutate(
        dimension = factor(dimension, levels = unique(dimension))
    ) %>%
    arrange(dimension, token) %>% 
    distinct() 
    
    
grep('[^ -~]', key_corporate_social_responsibility$regex, value = TRUE)
grep('[^ -~]', key_corporate_social_responsibility$token, value = TRUE)

pax::new_data(key_corporate_social_responsibility) # pax:::roxdat(key_regressive_imagery, 'key_regressive_imagery')
