pacman::p_load(xml2, rvest, tidyverse)

profanity_alvarez <- c("*damn", "*dyke", "*fuck*", "*shit*", "@$$", "ahole", "amcik",
"andskota", "anus", "arschloch", "arse*", "ash0le", "ash0les",
"asholes", "ass", "Ass Monkey", "Assface", "assh0le", "assh0lez",
"asshole", "assholes", "assholz", "assrammer", "asswipe", "ayir",
"azzhole", "b!+ch", "b!tch", "b00b*", "b00bs", "b17ch", "b1tch",
"bassterds", "bastard", "bastards", "bastardz", "basterds", "basterdz",
"bi+ch", "bi7ch", "Biatch", "bitch", "bitch*", "bitches", "Blow Job",
"blowjob", "boffing", "boiolas", "bollock*", "boobs", "breasts",
"buceta", "butt-pirate", "butthole", "buttwipe", "c0ck", "c0cks",
"c0k", "cabron", "Carpet Muncher", "cawk", "cawks", "cazzo",
"chink", "chraa", "chuj", "cipa", "clit", "Clit", "clits", "cnts",
"cntz", "cock", "cock-head", "cock-sucker", "Cock*", "cockhead",
"cocks", "CockSucker", "crap", "cum", "cunt", "cunt*", "cunts",
"cuntz", "d4mn", "daygo", "dego", "dick", "dick*", "dike*", "dild0",
"dild0s", "dildo", "dildos", "dilld0", "dilld0s", "dirsa", "dominatricks",
"dominatrics", "dominatrix", "dupa", "dyke", "dziwka", "ejackulate",
"ejakulate", "Ekrem*", "Ekto", "enculer", "enema", "f u c k",
"f u c k e r", "faen", "fag", "fag*", "fag1t", "faget", "fagg1t",
"faggit", "faggot", "fagit", "fags", "fagz", "faig", "faigs",
"fanculo", "fanny", "fart", "fatass", "fcuk", "feces", "feg",
"Felcher", "ficken", "fitt*", "Flikker", "flipping the bird",
"foreskin", "Fotze", "Fu(*", "fuck", "fucker", "fuckin", "fucking",
"fucks", "Fudge Packer", "fuk", "fuk*", "Fukah", "Fuken", "fuker",
"Fukin", "Fukk", "Fukkah", "Fukken", "Fukker", "Fukkin", "futkretzn",
"fux0r", "g00k", "gay", "gayboy", "gaygirl", "gays", "gayz",
"God-damned", "gook", "guiena", "h00r", "h0ar", "h0r", "h0re",
"h4x0r", "hell", "hells", "helvete", "hoar", "hoer", "hoer*",
"honkey", "hoor", "hoore", "hore", "Huevon", "hui", "injun",
"jackoff", "jap", "japs", "jerk-off", "jisim", "jism", "jiss",
"jizm", "jizz", "kanker*", "kawk", "kike", "klootzak", "knob",
"knobs", "knobz", "knulle", "kraut", "kuk", "kuksuger", "kunt",
"kunts", "kuntz", "Kurac", "kurwa", "kusi*", "kyrpa*", "l3i+ch",
"l3itch", "lesbian", "Lesbian", "lesbo", "Lezzian", "Lipshits",
"Lipshitz", "mamhoon", "masochist", "masokist", "massterbait",
"masstrbait", "masstrbate", "masterbaiter", "masterbat*", "masterbat3",
"masterbate", "masterbates", "masturbat*", "masturbate", "merd*",
"mibun", "mofo", "monkleigh", "Motha Fucker", "Motha Fuker",
"Motha Fukkah", "Motha Fukker", "mother-fucker", "Mother Fucker",
"Mother Fukah", "Mother Fuker", "Mother Fukkah", "Mother Fukker",
"motherfucker", "mouliewop", "muie", "mulkku", "muschi", "Mutha Fucker",
"Mutha Fukah", "Mutha Fuker", "Mutha Fukkah", "Mutha Fukker",
"n1gr", "nastt", "nazi", "nazis", "nepesaurio", "nigga", "nigger",
"nigger*", "nigger;", "nigur;", "niiger;", "niigr;", "nutsack",
"orafis", "orgasim;", "orgasm", "orgasum", "oriface", "orifice",
"orifiss", "orospu", "p0rn", "packi", "packie", "packy", "paki",
"pakie", "paky", "paska*", "pecker", "peeenus", "peeenusss",
"peenus", "peinus", "pen1s", "penas", "penis", "penis-breath",
"penus", "penuus", "perse", "Phuc", "phuck", "Phuck", "Phuk",
"Phuker", "Phukker", "picka", "pierdol*", "pillu*", "pimmel",
"pimpis", "piss*", "pizda", "polac", "polack", "polak", "Poonani",
"poontsee", "poop", "porn", "pr0n", "pr1c", "pr1ck", "pr1k",
"preteen", "pula", "pule", "pusse", "pussee", "pussy", "puta",
"puto", "puuke", "puuker", "qahbeh", "queef*", "queer", "queers",
"queerz", "qweers", "qweerz", "qweir", "rautenberg", "recktum",
"rectum", "retard", "s.o.b.", "sadist", "scank", "schaffer",
"scheiss*", "schlampe", "schlong", "schmuck", "screw", "screwing",
"scrotum", "semen", "sex", "sexy", "sh!+", "sh!t", "Sh!t", "sh!t*",
"sh1t", "sh1ter", "sh1ts", "sh1tter", "sh1tz", "sharmuta", "sharmute",
"shemale", "shi+", "shipal", "shit", "shits", "shitter", "Shitty",
"Shity", "shitz", "shiz", "Shyt", "Shyte", "Shytty", "Shyty",
"skanck", "skank", "skankee", "skankey", "skanks", "Skanky",
"skribz", "skurwysyn", "slut", "sluts", "Slutty", "slutz", "smut",
"son-of-a-bitch", "sphencter", "spic", "spierdalaj", "splooge",
"suka", "teets", "teez", "testical", "testicle", "testicle*",
"tit", "tits", "titt", "titt*", "turd", "twat", "va1jina", "vag1na",
"vagiina", "vagina", "vaj1na", "vajina", "vittu", "vullva", "vulva",
"w00se", "w0p", "wank", "wank*", "wetback*", "wh00r", "wh0re",
"whoar", "whore", "wichser", "wop*", "xrated", "xxx", "yed",
"zabourah")



pax::new_data(profanity_alvarez)
pax:::roxdat(profanity_alvarez, 'profanity_alvarez')
